services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: roman-app
    container_name: roman-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app

  db:
    image: postgres:14.1-alpine
    container_name: roman-db
    restart: always
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
    ports:
       - '5432:5432'
    volumes:
       - db:/var/lib/postgresql/data
    networks:
     - app

  nginx:
    image: nginx:alpine
    container_name: roman-nginx
    restart: unless-stopped
    ports:
      - 4444:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - app
networks:
  app:
    driver: bridge
volumes:
    db:
